### ISSUE TITLE
Replace custom gradle code with plugins instead

### ISSUE THREAD

**Issue by jutoft** [bmuschko/gradle-cargo-plugin#185]
The nebula.* plugins can cleanup the build script.
1. nebula.integtest sets up for a integrationTest folder.
The folder defaults to integTest so i suggest all the integrationTest files gets renamed.

    id "nebula.maven-publish" version "9.4.5"
    id "nebula.ivy-publish" version "9.4.5"
    id "nebula.javadoc-jar" version "9.4.5"
    id "nebula.source-jar" version "9.4.5"
Can be used to cleanup other parts of the build script.

**Comment by bmuschko** [comment]
From my experience, these plugins pull in a lot of transitive dependencies. Especially Maven plugin might not be compatible to the latest changes in Gradle in regards to the Maven Publish plugin. I know that the Nebula plugin had to use a lot of hacks that are likely not required anymore.

For this reason, let's not make the change for now.

We are not publishing to Ivy so that plugin wouldn't be required.
